name: Build All

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Android ARM64 Release

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up environment
      run: |
          echo "deb-src http://archive.ubuntu.com/ubuntu/ $(lsb_release -cs) main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list.d/ubuntu-source.list
          sudo apt update
          sudo apt build-dep -y mesa
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
          distribution: zulu
          java-version: 17
    - name: Download and install Android NDK
      run: |
          wget https://dl.google.com/android/repository/android-ndk-r27c-linux.zip
          unzip android-ndk-r27c-linux.zip
          export ANDROID_NDK_HOME=$(pwd)/android-ndk-r27c
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV
    - name: Set env vars
      run: |
          export TOOLCHAIN_FILE_CMAKE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
          echo "TOOLCHAIN_FILE_CMAKE=$TOOLCHAIN_FILE_CMAKE" >> $GITHUB_ENV
          export TOOLCHAIN=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64
          echo "TOOLCHAIN=$TOOLCHAIN" >> $GITHUB_ENV
          export ANDROID_API_LEVEL=30
          echo "ANDROID_API_LEVEL=$ANDROID_API_LEVEL" >> $GITHUB_ENV
          export ANDROID_ABI=arm64-v8a
          echo "ANDROID_ABI=$ANDROID_ABI" >> $GITHUB_ENV
          export BUILD_TYPE_CMAKE=Release
          echo "BUILD_TYPE_CMAKE=$BUILD_TYPE_CMAKE" >> $GITHUB_ENV
          export TARGET_TRIPLE=aarch64-linux-android
          echo "TARGET_TRIPLE=$TARGET_TRIPLE" >> $GITHUB_ENV
    - name: Build
      run: |
          chmod +x ./build-mesa.sh
          ./build-mesa.sh
          chmod +x ./build-jassimp.sh
          ./build-jassimp.sh
          chmod +x ./build-lwjgl-3.2.3.sh
          ./build-lwjgl-3.2.3.sh
          chmod +x ./build-lwjgl-3.3.6.sh
          ./build-lwjgl-3.3.6.sh
          chmod +x ./build-jniwrapper.sh
          ./build-jniwrapper.sh
    - name: Upload all built targets
      uses: actions/upload-artifact@v4
      with:
        name: targets
        path: targets
